services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-greentree}
      POSTGRES_USER: ${POSTGRES_USER:-greentree}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-greentree}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
